# Generated by Django 5.2.7 on 2025-10-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('Aventure', 'Aventure'), ('Stratégie', 'Stratégie'), ('Autre', 'Autre')], max_length=50)),
                ('ambiance', models.CharField(choices=[('Cyberpunk', 'Cyberpunk'), ('Fantasy', 'Fantasy'), ('Post-apocalyptique', 'Post-apocalyptique'), ('Historique', 'Historique'), ('Autre', 'Autre')], max_length=50)),
                ('mots_cles', models.CharField(max_length=200)),
                ('references', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
